docker:
  cpu:
    image: ${ASKCOS_REGISTRY}/atom_map/wln:1.0-cpu
    build: docker build -f Dockerfile_wln_cpu -t ${ASKCOS_REGISTRY}/atom_map/wln:1.0-cpu .
    start: sh scripts/serve_cpu_in_docker.sh
  gpu:
    image: ${ASKCOS_REGISTRY}/atom_map/wln:1.0-gpu
    build: docker build -f Dockerfile_wln_gpu -t ${ASKCOS_REGISTRY}/atom_map/wln:1.0-gpu .
    start: sh scripts/serve_gpu_in_docker.sh

singularity:
  cpu:
    image: wln_mapper_cpu.sif
    build: singularity build -f wln_mapper_cpu.sif singularity_wln_cpu.def
    start: sh scripts/serve_cpu_in_singularity.sh
  gpu:
    image: wln_mapper_gpu.sif
    build: singularity build -f wln_mapper_gpu.sif singularity_wln_gpu.def
    start: sh scripts/serve_gpu_in_singularity.sh

commands:
  stop-docker: docker stop atom_map_wln; docker rm atom_map_wln
  stop-singularity: singularity instance stop atom_map_wln
