import {
  mdiAccountCogOutline,
  mdiAccountKeyOutline,
  mdiAccountOffOutline,
  mdiAccountOutline,
  mdiAlertCircleOutline,
  mdiArrowCollapseAll,
  mdiArrowDown,
  mdiArrowExpandAll,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowRightBoldOutline,
  mdiArrowTopRight,
  mdiArrowUp,
  mdiAtom,
  mdiAutoFix,
  mdiBeakerOutline,
  mdiBookOpenOutline,
  mdiBookOpenPageVariantOutline,
  mdiCalculator,
  mdiCalculatorVariantOutline,
  mdiChartBellCurveCumulative,
  mdiChartScatterPlot,
  mdiCheck,
  mdiCheckCircleOutline,
  mdiCheckDecagramOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiClipboardTextOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiCogOutline,
  mdiCompare,
  mdiContentCopy,
  mdiContentSaveOutline,
  mdiCrosshairsGps,
  mdiCursorDefaultOutline,
  mdiDatabaseSearchOutline,
  mdiDeleteOutline,
  mdiDeleteRestore,
  mdiDeleteSweepOutline,
  mdiDotsHorizontal,
  mdiDownload,
  mdiDownloadOutline,
  mdiDraw,
  mdiEmailOutline,
  mdiEraser,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileAlertOutline,
  mdiFileCodeOutline,
  mdiFileDelimitedOutline,
  mdiFileDocumentMultipleOutline,
  mdiFileDocumentOutline,
  mdiFileExportOutline,
  mdiFileImportOutline,
  mdiFilterOutline,
  mdiFilterRemoveOutline,
  mdiFilterVariant,
  mdiFitToScreenOutline,
  mdiFlaskOutline,
  mdiFlaskPlusOutline,
  mdiFlaskRoundBottomOutline,
  mdiFolderMoveOutline,
  mdiFolderMultipleOutline,
  mdiFolderOpenOutline,
  mdiFolderOutline,
  mdiFolderPlusOutline,
  mdiFolderRemoveOutline,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiGraphOutline,
  mdiHistory,
  mdiImageOffOutline,
  mdiImageOutline,
  mdiInformationOutline,
  mdiKeyOutline,
  mdiLabelOffOutline,
  mdiLabelOutline,
  mdiLockOpenOutline,
  mdiLockOutline,
  mdiLogin,
  mdiMagnify,
  mdiMagnifyPlusOutline,
  mdiMenu,
  mdiMenuDown,
  mdiMinus,
  mdiMolecule,
  mdiOpenInNew,
  mdiPageFirst,
  mdiPauseCircleOutline,
  mdiPencil,
  mdiPencilOutline,
  mdiPlayOutline,
  mdiPlus,
  mdiProgressClock,
  mdiPulse,
  mdiRedo,
  mdiRefresh,
  mdiRotate3d,
  mdiScaleBalance,
  mdiSelectionRemove,
  mdiServerNetwork,
  mdiServerOff,
  mdiShieldAccountOutline,
  mdiShieldOutline,
  mdiShieldSearch,
  mdiSourceBranch,
  mdiStop,
  mdiStopCircleOutline,
  mdiSwapHorizontal,
  mdiTableArrowRight,
  mdiTableLarge,
  mdiTarget,
  mdiTextBoxSearchOutline,
  mdiThermometerLines,
  mdiTranslate,
  mdiTrashCanOutline,
  mdiUndo,
  mdiUpdate,
  mdiVectorPolylineEdit,
  mdiViewDashboardOutline,
  mdiViewGridOutline,
  mdiWaterOutline,
  mdiWeatherNight,
  mdiWeatherSunny,
} from "@mdi/js";

// Explicit imports keep unused library glyphs out of the production bundle.
export const iconPaths = Object.freeze({
  "mdi-account-cog-outline": mdiAccountCogOutline,
  "mdi-account-key-outline": mdiAccountKeyOutline,
  "mdi-account-off-outline": mdiAccountOffOutline,
  "mdi-account-outline": mdiAccountOutline,
  "mdi-alert-circle-outline": mdiAlertCircleOutline,
  "mdi-arrow-collapse-all": mdiArrowCollapseAll,
  "mdi-arrow-down": mdiArrowDown,
  "mdi-arrow-expand-all": mdiArrowExpandAll,
  "mdi-arrow-left": mdiArrowLeft,
  "mdi-arrow-right": mdiArrowRight,
  "mdi-arrow-right-bold-outline": mdiArrowRightBoldOutline,
  "mdi-arrow-top-right": mdiArrowTopRight,
  "mdi-arrow-up": mdiArrowUp,
  "mdi-atom": mdiAtom,
  "mdi-auto-fix": mdiAutoFix,
  "mdi-beaker-outline": mdiBeakerOutline,
  "mdi-book-open-outline": mdiBookOpenOutline,
  "mdi-book-open-page-variant-outline": mdiBookOpenPageVariantOutline,
  "mdi-calculator": mdiCalculator,
  "mdi-calculator-variant-outline": mdiCalculatorVariantOutline,
  "mdi-chart-bell-curve-cumulative": mdiChartBellCurveCumulative,
  "mdi-chart-scatter-plot": mdiChartScatterPlot,
  "mdi-check": mdiCheck,
  "mdi-check-circle-outline": mdiCheckCircleOutline,
  "mdi-check-decagram-outline": mdiCheckDecagramOutline,
  "mdi-chevron-down": mdiChevronDown,
  "mdi-chevron-left": mdiChevronLeft,
  "mdi-chevron-right": mdiChevronRight,
  "mdi-clipboard-text-outline": mdiClipboardTextOutline,
  "mdi-close": mdiClose,
  "mdi-close-circle": mdiCloseCircle,
  "mdi-close-circle-outline": mdiCloseCircleOutline,
  "mdi-cog-outline": mdiCogOutline,
  "mdi-compare": mdiCompare,
  "mdi-content-copy": mdiContentCopy,
  "mdi-content-save-outline": mdiContentSaveOutline,
  "mdi-crosshairs-gps": mdiCrosshairsGps,
  "mdi-cursor-default-outline": mdiCursorDefaultOutline,
  "mdi-database-search-outline": mdiDatabaseSearchOutline,
  "mdi-delete-outline": mdiDeleteOutline,
  "mdi-delete-restore": mdiDeleteRestore,
  "mdi-delete-sweep-outline": mdiDeleteSweepOutline,
  "mdi-dots-horizontal": mdiDotsHorizontal,
  "mdi-download": mdiDownload,
  "mdi-download-outline": mdiDownloadOutline,
  "mdi-draw": mdiDraw,
  "mdi-email-outline": mdiEmailOutline,
  "mdi-eraser": mdiEraser,
  "mdi-eye-off-outline": mdiEyeOffOutline,
  "mdi-eye-outline": mdiEyeOutline,
  "mdi-file-alert-outline": mdiFileAlertOutline,
  "mdi-file-code-outline": mdiFileCodeOutline,
  "mdi-file-delimited-outline": mdiFileDelimitedOutline,
  "mdi-file-document-multiple-outline": mdiFileDocumentMultipleOutline,
  "mdi-file-document-outline": mdiFileDocumentOutline,
  "mdi-file-export-outline": mdiFileExportOutline,
  "mdi-file-import-outline": mdiFileImportOutline,
  "mdi-filter-outline": mdiFilterOutline,
  "mdi-filter-remove-outline": mdiFilterRemoveOutline,
  "mdi-filter-variant": mdiFilterVariant,
  "mdi-fit-to-screen-outline": mdiFitToScreenOutline,
  "mdi-flask-outline": mdiFlaskOutline,
  "mdi-flask-plus-outline": mdiFlaskPlusOutline,
  "mdi-flask-round-bottom-outline": mdiFlaskRoundBottomOutline,
  "mdi-folder-move-outline": mdiFolderMoveOutline,
  "mdi-folder-multiple-outline": mdiFolderMultipleOutline,
  "mdi-folder-open-outline": mdiFolderOpenOutline,
  "mdi-folder-outline": mdiFolderOutline,
  "mdi-folder-plus-outline": mdiFolderPlusOutline,
  "mdi-folder-remove-outline": mdiFolderRemoveOutline,
  "mdi-format-list-bulleted": mdiFormatListBulleted,
  "mdi-format-list-numbered": mdiFormatListNumbered,
  "mdi-graph-outline": mdiGraphOutline,
  "mdi-history": mdiHistory,
  "mdi-image-off-outline": mdiImageOffOutline,
  "mdi-image-outline": mdiImageOutline,
  "mdi-information-outline": mdiInformationOutline,
  "mdi-key-outline": mdiKeyOutline,
  "mdi-label-off-outline": mdiLabelOffOutline,
  "mdi-label-outline": mdiLabelOutline,
  "mdi-lock-open-outline": mdiLockOpenOutline,
  "mdi-lock-outline": mdiLockOutline,
  "mdi-login": mdiLogin,
  "mdi-magnify": mdiMagnify,
  "mdi-magnify-plus-outline": mdiMagnifyPlusOutline,
  "mdi-menu": mdiMenu,
  "mdi-menu-down": mdiMenuDown,
  "mdi-minus": mdiMinus,
  "mdi-molecule": mdiMolecule,
  "mdi-open-in-new": mdiOpenInNew,
  "mdi-page-first": mdiPageFirst,
  "mdi-pause-circle-outline": mdiPauseCircleOutline,
  "mdi-pencil": mdiPencil,
  "mdi-pencil-outline": mdiPencilOutline,
  "mdi-play-outline": mdiPlayOutline,
  "mdi-plus": mdiPlus,
  "mdi-progress-clock": mdiProgressClock,
  "mdi-pulse": mdiPulse,
  "mdi-redo": mdiRedo,
  "mdi-refresh": mdiRefresh,
  "mdi-rotate-3d": mdiRotate3d,
  "mdi-scale-balance": mdiScaleBalance,
  "mdi-selection-remove": mdiSelectionRemove,
  "mdi-server-network": mdiServerNetwork,
  "mdi-server-off": mdiServerOff,
  "mdi-shield-account-outline": mdiShieldAccountOutline,
  "mdi-shield-outline": mdiShieldOutline,
  "mdi-shield-search": mdiShieldSearch,
  "mdi-source-branch": mdiSourceBranch,
  "mdi-stop": mdiStop,
  "mdi-stop-circle-outline": mdiStopCircleOutline,
  "mdi-swap-horizontal": mdiSwapHorizontal,
  "mdi-table-arrow-right": mdiTableArrowRight,
  "mdi-table-large": mdiTableLarge,
  "mdi-target": mdiTarget,
  "mdi-text-box-search-outline": mdiTextBoxSearchOutline,
  "mdi-thermometer-lines": mdiThermometerLines,
  "mdi-translate": mdiTranslate,
  "mdi-trash-can-outline": mdiTrashCanOutline,
  "mdi-undo": mdiUndo,
  "mdi-update": mdiUpdate,
  "mdi-vector-polyline-edit": mdiVectorPolylineEdit,
  "mdi-view-dashboard-outline": mdiViewDashboardOutline,
  "mdi-view-grid-outline": mdiViewGridOutline,
  "mdi-water-outline": mdiWaterOutline,
  "mdi-weather-night": mdiWeatherNight,
  "mdi-weather-sunny": mdiWeatherSunny,
});
