import numpy as np
import os
from wln.rank.mol_graph import smiles2graph
from wln.rank.utils import enumerate_outcomes
from wln.wrapper import TFSavedModelWrapper


class WLNCandidateRanker:
    def __init__(self, cutoff=1500, core_size=16, **kwargs):
        """
        Initialize WLNCandidateRanker

        Args:
            cutoff (int, optional): max number of candidates to consider
            core_size (int, optional): max number of core bonds to consider
        """
        self.cutoff = cutoff
        self.core_size = core_size
        self.model = None

    def load(self, model_name="uspto_500k"):
        """
        Load TensorFlow model from saved model file defined in global_config.py

        Args:
            model_name (str, optional): model key defined in global_config.py
        """
        path = os.path.join("data", model_name, "rank", "1")
        self.model = TFSavedModelWrapper(
            path=path,
            dtypes=["float32", "float32", "float32", "float32", "int32", "float32"],
        )

    def predict(self, smiles, candidate_bonds, top_n=100, atommap=False):
        """
        Predict candidate ranks for the input SMILES and candidate bonds

        Args:
            smiles (str): SMILES of input reactants
            candidate_bonds (list): candidates generated by WLNPairwiseAtomClassifier
            top_n (int, optional): number of predicted outcomes to return
            atommap (bool, optional): whether to keep atom map numbers in output
        """
        inputs, conf = smiles2graph(
            smiles,
            None,
            candidate_bonds,
            None,
            cutoff=self.cutoff,
            core_size=self.core_size,
            testing=True,
        )
        inputs = [np.expand_dims(inp, axis=0) for inp in inputs]
        outputs = self.model.predict(inputs)
        return enumerate_outcomes(smiles, conf, outputs, top_n=top_n, atommap=atommap)
