from rdkit import Chem
import tensorflow as tf
import re

from wln.constants import BOND_ORDER_TO_INDEX, BOND_TYPES
from wln.utils import get_atom_idx
from wln.rank.eval_by_smiles import edit_mol_smiles

def focus_mol(mol, cbonds):
    """
    Create mol only based on smiles that are involved in cbonds
    Remaining smiles are added to a list

    args: 
        mol (Chem.Mol): reactant mol
        cbonds (list of tuples): bond edits involved

    """
    
    atoms_involved_edit = [atom for cbond in cbonds for atom in cbond[:2]]
    reactants = Chem.MolToSmiles(mol)
    unchanged_smiles = []
    reactant_list = reactants.split(".")

    focused_smiles = ''
    for reactant in reactant_list:
        atom_map = re.findall(r':(\d+)', reactant)
        atom_map = [int(n)-1 for n in atom_map]
        if set(atom_map) & set(atoms_involved_edit):
            focused_smiles += f".{reactant}"
        else:
            reac_mol = Chem.MolFromSmiles(reactant)
            [atom.ClearProp("molAtomMapNumber") for atom in reac_mol.GetAtoms()]
            reactant = Chem.MolToSmiles(reac_mol)
            unchanged_smiles.append(reactant)
    focused_mol = Chem.MolFromSmiles(focused_smiles[1:])
    return focused_mol, unchanged_smiles

def enumerate_outcomes(rsmi, conf, scores, top_n=100, atommap=False):
    """
    Function to enumerate the outcomes based on the edit scores generated by WLNCandidateRanker model

    args:
        rsmi (str): reactant SMILES
        conf (list of tuples):
        scores (array): Numpy array of candidate scores shape=(1, cutoff)
        top_n (int): How many outcomes to enumerate

    """
    scores = tf.squeeze(scores, axis=0)
    tk = tf.minimum(top_n, tf.shape(scores)[0])
    _, topk = tf.nn.top_k(scores, k=tk)
    topk = topk.numpy()

    # Don't waste predictions on bond changes that aren't actually changes
    rmol = Chem.MolFromSmiles(rsmi)
    rbonds = {}
    for bond in rmol.GetBonds():
        a1 = get_atom_idx(bond.GetBeginAtom())
        a2 = get_atom_idx(bond.GetEndAtom())
        t = BOND_TYPES.index(bond.GetBondType())
        a1, a2 = min(a1, a2), max(a1, a2)
        rbonds[(a1, a2)] = t

    cand_smiles = []
    cand_scores = []
    for idx in topk:
        cbonds = []
        # Define edits from prediction
        for x, y, t, v in conf[idx]:
            if ((x, y) not in rbonds and t > 0) or (
                (x, y) in rbonds and rbonds[(x, y)] != t
            ):
                cbonds.append((x, y, BOND_ORDER_TO_INDEX[t]))

        focused_rmol, rem_smiles = focus_mol(rmol, cbonds)
        pred_smiles = edit_mol_smiles(focused_rmol, cbonds, atommap=atommap)
        pred_smiles += rem_smiles
        pred_smiles = set(pred_smiles)
        if pred_smiles in cand_smiles:
            continue
        else:
            cand_smiles.append(pred_smiles)
            cand_scores.append(scores[idx])

    cand_probs = tf.nn.softmax(cand_scores)

    outcomes = []
    for i in range(min(len(cand_smiles), top_n)):
        outcomes.append(
            {
                "rank": i + 1,
                "smiles": ".".join(list(cand_smiles[i])),
                "score": float(cand_scores[i].numpy()),
                "prob": float(cand_probs[i].numpy()),
            }
        )

    return outcomes
