FROM mambaorg/micromamba:1.4.7

USER root
# Keep the base environment activated
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_REMOTE_CONNECT_TIMEOUT_SECS=60 \
    MAMBA_REMOTE_READ_TIMEOUT_SECS=600 \
    MAMBA_REMOTE_MAX_RETRIES=5
RUN apt update && apt -y install git gcc g++ make

RUN micromamba install -y python=3.11.13 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
RUN pip install torch==2.7.1 --index-url https://download.pytorch.org/whl/cpu
RUN pip install \
    aimsim==2.2.2 \
    astartes==1.3.1 \
    chemprop==2.2.0 \
    configargparse==1.7.1 \
    descriptastorus==2.8.0 \
    fastapi==0.116.1 \
    numpy==2.3.1 \
    pandas==2.3.1 \
    pytorch-lightning==2.5.2 \
    pillow==11.3.0 \
    prometheus-client==0.22.1 \
    pydantic==2.11.7 \
    rdkit==2025.3.3 \
    requests==2.32.5 \
    rich==14.0.0 \
    scikit-learn==1.7.0 \
    scipy==1.16.0 \
    urllib3==2.5.0 \
    uvicorn==0.35.0 \
    zipp==3.20.2

COPY . /app/solubility_fusion_cycle
WORKDIR /app/solubility_fusion_cycle

EXPOSE 9771

ENV CUDA_VISIBLE_DEVICES 10

CMD ["python", "Fusion_Cycle_Server.py"]
