FROM mambaorg/micromamba:1.4.7

USER root
# Keep the base environment activated
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_REMOTE_CONNECT_TIMEOUT_SECS=60 \
    MAMBA_REMOTE_READ_TIMEOUT_SECS=600 \
    MAMBA_REMOTE_MAX_RETRIES=5
RUN apt update && apt -y install git gcc g++ make

# Install required packages with micromamba
RUN micromamba install -y python=3.8.17 pip=23.2.1 rdkit=2020.09.5 openjdk=11.0.15 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
RUN micromamba install -y pytorch=1.12.1 cpuonly "mkl>=2022.1,<2023" -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
RUN micromamba install -y chemprop_solvation=0.0.3 coolprop=6.4.1 descriptastorus=2.2.0 numpy=1.19.4 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge -c fhvermei -c rmg
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install \
    torch-model-archiver==0.3.1 \
    torchserve==0.3.1 \
    tqdm==4.66.1

# Copy configuration files
COPY torchserve/config.properties /home/askcos/config.properties

# Copy the application code
COPY ./solvation_predictor /home/askcos/solprop/solvation_predictor
COPY ./torchserve/solprop.mar /home/askcos/model_store/solprop.mar

# Expose necessary ports
EXPOSE 9732 9733 9734

# Set the working directory
WORKDIR /home/askcos

# Set environment variables
ENV PYTHONPATH=/home/askcos/solprop

# Set the entrypoint and command
#ENTRYPOINT ["torchserve", "--start", "--foreground", "--ts-config", "/home/askcos/config.properties"]
#CMD ["--models", "all"]
