// flow-typed signature: 9e30217c85f024b20338f72d2c1e60bb
// flow-typed version: <<STUB>>/@vitejs/plugin-vue_v^4.0.0/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vitejs/plugin-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vitejs/plugin-vue' {
  declare module.exports: any;
}
