FROM mambaorg/micromamba:1.4.7

USER root
# Keep the base environment activated
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_REMOTE_CONNECT_TIMEOUT_SECS=60 \
    MAMBA_REMOTE_READ_TIMEOUT_SECS=600 \
    MAMBA_REMOTE_MAX_RETRIES=5
RUN apt update && apt -y install git gcc g++ make

# Use micromamba to resolve conda-forge, much faster than conda
RUN micromamba install -y python=3.8.17 pip=20.0.2 rdkit=2020.09.5 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install \
    fastapi==0.95.1 \
    pillow==10.1.0 \
    protobuf==3.19.0 \
    pydantic==1.10.12 \
    rdchiral==1.1.0 \
    requests==2.31.0 \
    scikit-learn==1.0.2 \
    scipy==1.7.3 \
    tensorflow-cpu==2.7.4 \
    urllib3==1.26.16 \
    uvicorn==0.21.1 \
    zipp==3.20.2

COPY . /app/wldn5
WORKDIR /app/wldn5

EXPOSE 9501

ENV CUDA_VISIBLE_DEVICES 10

CMD ["python", "wldn5_server.py"]
