FROM mambaorg/micromamba:1.4.7-bionic-cuda-11.3.1

USER root
# Keep the base environment activated
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_REMOTE_CONNECT_TIMEOUT_SECS=60 \
    MAMBA_REMOTE_READ_TIMEOUT_SECS=600 \
    MAMBA_REMOTE_MAX_RETRIES=5
RUN apt update && apt -y install git gcc g++ make

# Install required packages with micromamba
RUN micromamba install -y python=3.8.17 pip=23.2.1 rdkit=2023.09.1 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
RUN micromamba install -y pytorch torchvision torchaudio pytorch-cuda=11.8 "mkl>=2022.1,<2023" -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch -c nvidia
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install \
    fastapi==0.95.1 \
    pillow==10.1.0 \
    protobuf==3.19.0 \
    pydantic==1.10.12 \
    requests==2.31.0 \
    scikit-learn>=0.22.2.post1 \
    scipy==1.9.0 \
    descriptastorus==2.6.1 \
    pandas==1.4.2 \
    tqdm==4.66.1 \
    urllib3==1.26.11 \
    uvicorn==0.21.1 \
    typed-argument-parser==1.7.2

COPY . /app/qm_descriptors
WORKDIR /app/qm_descriptors/code
RUN /opt/conda/bin/python -m pip install -e .
WORKDIR /app/qm_descriptors

EXPOSE 9602

ENV CUDA_VISIBLE_DEVICES 10

CMD ["python", "qm_descriptors_server.py"]
