FROM mambaorg/micromamba:1.4.7-bionic-cuda-11.3.1

USER root
# Keep the base environment activated
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_REMOTE_CONNECT_TIMEOUT_SECS=60 \
    MAMBA_REMOTE_READ_TIMEOUT_SECS=600 \
    MAMBA_REMOTE_MAX_RETRIES=5
RUN apt update && apt -y install gcc g++ make

# Use micromamba to resolve conda-forge, much faster than conda
RUN micromamba install -y python=3.8 pip=20.0.2 rdkit=2020.09.5 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
RUN micromamba install -y pytorch==1.12.1 cudatoolkit=11.3 "mkl>=2022.1,<2023" -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install \
    fastapi==0.95.1 \
    protobuf==3.19.0 \
    pydantic==1.10.12 \
    requests==2.31.0 \
    scipy==1.7.3 \
    uvicorn==0.21.1

COPY . /app/descriptors
WORKDIR /app/descriptors

EXPOSE 9631

CMD ["python", "descriptor_server.py"]
