FROM mambaorg/micromamba:1.4.7

USER root
# Keep the base environment activated
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_REMOTE_CONNECT_TIMEOUT_SECS=60 \
    MAMBA_REMOTE_READ_TIMEOUT_SECS=600 \
    MAMBA_REMOTE_MAX_RETRIES=5
RUN apt update && apt -y install git gcc g++ make

# Use micromamba to resolve conda-forge, much faster than conda
RUN micromamba install -y python=3.10.12 pip=23.2.1 rdkit=2023.03.3 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install \
    bcrypt==4.3.0 \
    celery==5.2.7 \
    epam.indigo==1.32.0 \
    fastapi==0.95.1 \
    hdbscan==0.8.33 \
    gevent==22.10.2 \
    networkx==2.6.3 \
    pandas==1.5.3 \
    "passlib[bcrypt]"==1.7.4 \
    pillow==10.1.0 \
    prometheus-client==0.22.1 \
    protobuf==3.19.0 \
    pulp==2.6.0 \
    pydantic==1.10.12 \
    pymongo==4.4.1 \
    pytest==7.4.1 \
    "python-jose[cryptography]"==3.3.0 \
    python-multipart==0.0.6 \
    pyyaml==6.0.1 \
    redis==4.3.6 \
    requests==2.31.0 \
    scikit-learn==1.0.2 \
    scipy==1.7.3 \
    svgutils==0.3.4 \
    tqdm==4.66.1 \
    uvicorn==0.21.1

COPY . /app/pmi_calculator
WORKDIR /app/pmi_calculator

EXPOSE 9701

ENV CUDA_VISIBLE_DEVICES 10

CMD ["python", "pmi_server.py"]
