# FROM mambaorg/micromamba:1.4.7-bionic-cuda-11.3.1
FROM mambaorg/micromamba:1.5.8-jammy-cuda-12.1.1

USER root
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_REMOTE_CONNECT_TIMEOUT_SECS=60 \
    MAMBA_REMOTE_READ_TIMEOUT_SECS=600 \
    MAMBA_REMOTE_MAX_RETRIES=5

RUN apt update && apt -y install git gcc g++ make

RUN micromamba install -y \
    python=3.11.2 \
    pip=25.1.1 \
    rdkit=2023.09.5 \
    pandas=2.3.1 \
    pytorch=2.1.0 \
    pytorch-cuda=12.1 \
    pytorch-lightning=2.1.4 \
    -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch -c nvidia -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install \
fastapi==0.88.0 \
uvicorn==0.35.0 \
pydantic==1.10.22 \
requests==2.32.4 \
loguru==0.7.3 \
tqdm==4.67.1 \
numpy==1.26.4 \
tensorboard==2.18.0 \
torcheval==0.0.7 \
chemprop==2.0.0 \
optuna==4.4.0

COPY . /app/quarc
WORKDIR /app/quarc

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install --no-deps -e .


EXPOSE 9921
