// flow-typed signature: aa196538731c0459035318e33f3362dd
// flow-typed version: <<STUB>>/@vue/test-utils_v^2.4.0-alpha.2/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vue/test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vue/test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vue/test-utils/dist/vue-test-utils.browser' {
  declare module.exports: any;
}

declare module '@vue/test-utils/dist/vue-test-utils.cjs' {
  declare module.exports: any;
}

declare module '@vue/test-utils/dist/vue-test-utils.esm-browser' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vue/test-utils/dist/vue-test-utils.browser.js' {
  declare module.exports: $Exports<'@vue/test-utils/dist/vue-test-utils.browser'>;
}
declare module '@vue/test-utils/dist/vue-test-utils.cjs.js' {
  declare module.exports: $Exports<'@vue/test-utils/dist/vue-test-utils.cjs'>;
}
declare module '@vue/test-utils/dist/vue-test-utils.esm-browser.js' {
  declare module.exports: $Exports<'@vue/test-utils/dist/vue-test-utils.esm-browser'>;
}
