// flow-typed signature: b99e780438b02bf23a4867c7cd6081f3
// flow-typed version: <<STUB>>/@vue/vue3-jest_v^29.2.5/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vue/vue3-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vue/vue3-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vue/vue3-jest/lib/constants' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/ensure-require' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/generate-code' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/map-lines' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/module-name-mapper-helper' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/process-custom-blocks' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/process-style' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/process' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/throw-error' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/transformers/coffee' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/transformers/typescript' {
  declare module.exports: any;
}

declare module '@vue/vue3-jest/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vue/vue3-jest/lib/constants.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/constants'>;
}
declare module '@vue/vue3-jest/lib/ensure-require.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/ensure-require'>;
}
declare module '@vue/vue3-jest/lib/generate-code.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/generate-code'>;
}
declare module '@vue/vue3-jest/lib/index' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib'>;
}
declare module '@vue/vue3-jest/lib/index.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib'>;
}
declare module '@vue/vue3-jest/lib/map-lines.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/map-lines'>;
}
declare module '@vue/vue3-jest/lib/module-name-mapper-helper.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/module-name-mapper-helper'>;
}
declare module '@vue/vue3-jest/lib/process-custom-blocks.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/process-custom-blocks'>;
}
declare module '@vue/vue3-jest/lib/process-style.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/process-style'>;
}
declare module '@vue/vue3-jest/lib/process.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/process'>;
}
declare module '@vue/vue3-jest/lib/throw-error.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/throw-error'>;
}
declare module '@vue/vue3-jest/lib/transformers/coffee.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/transformers/coffee'>;
}
declare module '@vue/vue3-jest/lib/transformers/typescript.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/transformers/typescript'>;
}
declare module '@vue/vue3-jest/lib/utils.js' {
  declare module.exports: $Exports<'@vue/vue3-jest/lib/utils'>;
}
