// flow-typed signature: 62310c9d82afaf014a013b570ea52d14
// flow-typed version: <<STUB>>/roboto-fontface_v*/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'roboto-fontface'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'roboto-fontface' {
  declare module.exports: any;
}
