// flow-typed signature: 223761574d5387df8e3a4e81430dad77
// flow-typed version: <<STUB>>/vue-router_v^4.0.0/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-router/dist/vue-router.cjs' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.cjs.prod' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.esm-browser' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.esm-bundler' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.global' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.global.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-router/dist/vue-router.cjs.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.cjs'>;
}
declare module 'vue-router/dist/vue-router.cjs.prod.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.cjs.prod'>;
}
declare module 'vue-router/dist/vue-router.esm-browser.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.esm-browser'>;
}
declare module 'vue-router/dist/vue-router.esm-bundler.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.esm-bundler'>;
}
declare module 'vue-router/dist/vue-router.global.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.global'>;
}
declare module 'vue-router/dist/vue-router.global.prod.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.global.prod'>;
}
declare module 'vue-router/index' {
  declare module.exports: $Exports<'vue-router'>;
}
declare module 'vue-router/index.js' {
  declare module.exports: $Exports<'vue-router'>;
}
