// flow-typed signature: 1653984a84948d95c43366d6175faf62
// flow-typed version: <<STUB>>/vue_v^3.2.0/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue/compiler-sfc' {
  declare module.exports: any;
}

declare module 'vue/compiler-sfc/register-ts' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.cjs' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.cjs.prod' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.esm-browser' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.esm-browser.prod' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.esm-bundler' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.global' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.global.prod' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.runtime.esm-browser' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.runtime.esm-browser.prod' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.runtime.esm-bundler' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.runtime.global' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.runtime.global.prod' {
  declare module.exports: any;
}

declare module 'vue/jsx-runtime' {
  declare module.exports: any;
}

declare module 'vue/server-renderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue/compiler-sfc/index' {
  declare module.exports: $Exports<'vue/compiler-sfc'>;
}
declare module 'vue/compiler-sfc/index.js' {
  declare module.exports: $Exports<'vue/compiler-sfc'>;
}
declare module 'vue/compiler-sfc/register-ts.js' {
  declare module.exports: $Exports<'vue/compiler-sfc/register-ts'>;
}
declare module 'vue/dist/vue.cjs.js' {
  declare module.exports: $Exports<'vue/dist/vue.cjs'>;
}
declare module 'vue/dist/vue.cjs.prod.js' {
  declare module.exports: $Exports<'vue/dist/vue.cjs.prod'>;
}
declare module 'vue/dist/vue.esm-browser.js' {
  declare module.exports: $Exports<'vue/dist/vue.esm-browser'>;
}
declare module 'vue/dist/vue.esm-browser.prod.js' {
  declare module.exports: $Exports<'vue/dist/vue.esm-browser.prod'>;
}
declare module 'vue/dist/vue.esm-bundler.js' {
  declare module.exports: $Exports<'vue/dist/vue.esm-bundler'>;
}
declare module 'vue/dist/vue.global.js' {
  declare module.exports: $Exports<'vue/dist/vue.global'>;
}
declare module 'vue/dist/vue.global.prod.js' {
  declare module.exports: $Exports<'vue/dist/vue.global.prod'>;
}
declare module 'vue/dist/vue.runtime.esm-browser.js' {
  declare module.exports: $Exports<'vue/dist/vue.runtime.esm-browser'>;
}
declare module 'vue/dist/vue.runtime.esm-browser.prod.js' {
  declare module.exports: $Exports<'vue/dist/vue.runtime.esm-browser.prod'>;
}
declare module 'vue/dist/vue.runtime.esm-bundler.js' {
  declare module.exports: $Exports<'vue/dist/vue.runtime.esm-bundler'>;
}
declare module 'vue/dist/vue.runtime.global.js' {
  declare module.exports: $Exports<'vue/dist/vue.runtime.global'>;
}
declare module 'vue/dist/vue.runtime.global.prod.js' {
  declare module.exports: $Exports<'vue/dist/vue.runtime.global.prod'>;
}
declare module 'vue/index' {
  declare module.exports: $Exports<'vue'>;
}
declare module 'vue/index.js' {
  declare module.exports: $Exports<'vue'>;
}
declare module 'vue/jsx-runtime/index' {
  declare module.exports: $Exports<'vue/jsx-runtime'>;
}
declare module 'vue/jsx-runtime/index.js' {
  declare module.exports: $Exports<'vue/jsx-runtime'>;
}
declare module 'vue/server-renderer/index' {
  declare module.exports: $Exports<'vue/server-renderer'>;
}
declare module 'vue/server-renderer/index.js' {
  declare module.exports: $Exports<'vue/server-renderer'>;
}
