docker:
  cpu:
    image: ${ASKCOS_REGISTRY}/retro/template_enumeration:1.0-cpu
    build: docker build -f Dockerfile_cpu -t ${ASKCOS_REGISTRY}/retro/template_enumeration:1.0-cpu .
    start: sh scripts/serve_cpu_in_docker.sh

commands:
  stop-docker: docker stop retro_template_enumeration; docker rm retro_template_enumeration
