import glob
import json
from rdchiral.initialization import rdchiralReactants, rdchiralReaction
from rdchiral.main import rdchiralRun
from rdkit import Chem
from typing import Any, Dict, List, Tuple


def canonicalize_smiles(smiles: str, remove_atom_number: bool = True) -> str:
    """Adapted from Molecular Transformer"""
    smiles = "".join(smiles.split())
    cano_smiles = ""

    mol = Chem.MolFromSmiles(smiles)

    if mol is not None:
        if remove_atom_number:
            [a.ClearProp('molAtomMapNumber') for a in mol.GetAtoms()]

        cano_smiles = Chem.MolToSmiles(mol, isomericSmiles=True, canonical=True)
        # Sometimes stereochem takes another canonicalization... (just in case)
        mol = Chem.MolFromSmiles(cano_smiles)
        if mol is not None:
            cano_smiles = Chem.MolToSmiles(mol, isomericSmiles=True, canonical=True)

    return cano_smiles


class TemplateEnumerator:
    def __init__(self):
        self.templates = self._load_templates_as_lists(path="./data")

    @staticmethod
    def _load_templates_as_lists(path: str) -> Dict[str, List[Dict[str, Any]]]:
        templates = {}

        template_files = glob.glob(f"{path}/*.json")
        for template_file in template_files:
            with open(template_file, "r") as f:
                data = json.load(f)
            for template in data:
                assert "reaction_smarts" in template
                assert "template_set" in template

                template_set = template["template_set"]
                if template_set in templates:
                    templates[template_set].append(template)
                else:
                    templates[template_set] = [template]

        print("Loaded templates. Template count:")
        [print(f"{template_set}: {len(data)}") for template_set, data in templates.items()]

        return templates

    def enumerate(
        self,
        target_product_smiles: str,
        template_set: str
    ) -> Tuple[List[str], List[Dict[str, Any]], List[float]]:
        reactants = []
        templates = []
        scores = []

        all_templates = self.templates[template_set]
        for template in all_templates:
            # IMPORTANT MAGIC from v1. DO NOT TOUCH
            # Force reactants and products to be one pseudo-molecule (bookkeeping)
            reaction_smarts = template["reaction_smarts"]
            reaction_smarts_one = "(" + reaction_smarts.replace(">>", ")>>(") + ")"
            rxn = rdchiralReaction(str(reaction_smarts_one))
            prod = rdchiralReactants(target_product_smiles)
            try:
                # New: set return_mapped to False. Remap after in expand_one
                precursors = rdchiralRun(rxn, prod, return_mapped=False)
            except:
                continue  # unknown error in rdchiral

            if not precursors:  # empty precursors
                continue

            template = {k: v for k, v in template.items()
                        if k not in ["references", "rxn"]}

            for precursor in precursors:
                # here we just return the full template with metadata
                # in theory it should also be fetchable from the DB
                # iff we decide to seed it later
                smiles_list = precursor.split(".")
                if template.get("intra_only") and len(smiles_list) > 1:
                    # Disallowed intermolecular reaction
                    continue
                if template.get("dimer_only") and (
                        len(set(smiles_list)) != 1 or len(smiles_list) != 2
                ):
                    # Not a dimer
                    continue
                if target_product_smiles in smiles_list:
                    # Skip if no transformation happened
                    continue

                # joined_smiles = ".".join(sorted(smiles_list))
                # if joined_smiles in smiles_to_index:
                #     # Precursor was already generated by another template
                #     # -> update metadata. Templates are ordered by score, so
                #     # no need to update template score or rank
                #     res = result["templates"][
                #         smiles_to_index[joined_smiles]
                #     ]
                #     if template["_id"] not in res["tforms"]:
                #         res["tforms"].append(template["_id"])
                #     res["num_examples"] += template["count"]
                # else:
                #     # New precursor -> generate metadata
                #     template["tforms"] = [template["_id"]]
                #     template["num_examples"] = template["count"]
                #     smiles_to_index[joined_smiles] = len(result["templates"])

                # Here we use a different logic as compared to metadata consolidation in template relevance
                # assuming the user wants to keep *everything* and not necessarily merging
                # for same reactants from multiple templates

                reactants.append(precursor)
                templates.append(template)
                scores.append(0.0)

            del rxn, prod

        return reactants, templates, scores
