// flow-typed signature: 6eb11d76e393e816085bf7bdf341c812
// flow-typed version: <<STUB>>/eslint-plugin-vue_v^9.3.0/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-vue/lib/configs/base' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/essential' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/no-layout-rules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/strongly-recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/vue3-essential' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/vue3-recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/vue3-strongly-recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/meta' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/processor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/removed-rules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/array-bracket-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/array-bracket-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/array-element-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/arrow-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/attribute-hyphenation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/attributes-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/block-lang' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/block-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/block-tag-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/brace-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/camelcase' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/comma-dangle' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/comma-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/comma-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/comment-directive' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/component-api-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/component-definition-name-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/component-name-in-template-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/component-options-name-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/component-tags-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/custom-event-name-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/define-emits-declaration' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/define-macros-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/define-props-declaration' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/dot-location' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/dot-notation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/eqeqeq' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/first-attribute-linebreak' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/func-call-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-button-has-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-comment-content-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-comment-content-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-comment-indent' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-end-tags' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-indent' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-quotes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-self-closing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/jsx-uses-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/key-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/keyword-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/match-component-file-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/match-component-import-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/max-attributes-per-line' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/max-len' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/max-lines-per-block' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/multi-word-component-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/multiline-html-element-content-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/multiline-ternary' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/mustache-interpolation-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/new-line-between-multi-line-property' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/next-tick-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-arrow-functions-in-watch' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-async-in-computed-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-bare-strings-in-template' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-boolean-default' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-child-content' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-computed-properties-in-data' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-console' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-constant-condition' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-custom-modifiers-on-v-model' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-data-object-declaration' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-destroyed-lifecycle' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-dollar-listeners-api' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-dollar-scopedslots-api' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-events-api' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-filter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-functional-template' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-html-element-is' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-inline-template' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-props-default-this' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-router-link-tag-prop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-scope-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-slot-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-slot-scope-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-v-bind-sync' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-v-is' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-v-on-native-modifier' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-v-on-number-modifiers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-vue-config-keycodes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-dupe-keys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-dupe-v-else-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-duplicate-attr-inheritance' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-duplicate-attributes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-empty-component-block' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-empty-pattern' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-export-in-script-setup' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-expose-after-await' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-extra-parens' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-invalid-model-keys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-irregular-whitespace' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-lifecycle-after-await' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-lone-template' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-loss-of-precision' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-multi-spaces' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-multiple-objects-in-class' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-multiple-slot-args' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-multiple-template-root' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-mutating-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-parsing-error' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-potential-component-option-typo' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-ref-as-operand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-ref-object-destructure' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-required-prop-with-default' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-reserved-component-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-reserved-keys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-reserved-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-block' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-call-after-await' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-class' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-component-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-component-options' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-custom-event' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-html-elements' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-static-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-syntax' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-v-bind' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-root-v-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-setup-props-destructure' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-shared-component-data' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-side-effects-in-computed-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-spaces-around-equal-signs-in-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-sparse-arrays' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-static-inline-styles' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-template-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-template-shadow' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-template-target-blank' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-textarea-mustache' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-this-in-before-route-enter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-undef-components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-undef-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-unsupported-features' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-unused-components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-unused-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-unused-refs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-unused-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-use-computed-property-like-method' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-use-v-if-with-v-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-useless-concat' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-useless-mustaches' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-useless-template-attributes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-useless-v-bind' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-v-for-template-key-on-child' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-v-for-template-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-v-html' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-v-model-argument' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-v-text-v-html-on-component' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-v-text' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-watch-after-await' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/object-curly-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/object-curly-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/object-property-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/object-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/one-component-per-file' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/operator-linebreak' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/order-in-components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/padding-line-between-blocks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/padding-line-between-tags' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/padding-lines-in-component-definition' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/prefer-define-options' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/prefer-import-from-vue' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/prefer-prop-type-boolean-first' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/prefer-separate-static-class' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/prefer-template' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/prefer-true-attribute-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/prop-name-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/quote-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-component-is' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-default-prop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-direct-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-emit-validator' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-explicit-emits' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-expose' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-macro-variable-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-name-property' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-prop-comment' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-prop-type-constructor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-prop-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-render-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-slots-as-functions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-toggle-inside-transition' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-typed-ref' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-v-for-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-valid-default-prop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/return-in-computed-property' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/return-in-emits-validator' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/script-indent' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/script-setup-uses-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/singleline-html-element-content-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/sort-keys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/space-in-parens' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/space-infix-ops' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/space-unary-ops' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/static-class-names-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/define-options' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/define-slots' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/dynamic-directive-arguments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/is-attribute-with-vue-prefix' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/scope-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/script-setup' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/slot-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/slot-scope-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/style-css-vars-injection' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/utils/can-convert-to-v-slot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-bind-attr-modifier' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-bind-prop-modifier-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-is' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-memo' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-model-argument' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-model-custom-modifiers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-slot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/template-curly-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/this-in-template' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/use-v-on-exact' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-bind-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-for-delimiter-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-on-event-hyphenation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-on-function-call' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-on-handler-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-on-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-slot-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-attribute-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-define-emits' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-define-options' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-define-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-model-definition' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-next-tick' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-template-root' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-bind-sync' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-bind' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-cloak' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-else-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-else' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-html' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-is' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-memo' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-model' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-on' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-once' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-pre' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-show' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-slot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-text' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/comments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/html-comments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/indent-common' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/indent-ts' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/indent-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/keycode-to-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/property-references' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/ref-object-references' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/regexp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/selector' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/style-variables' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/ts-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/ts-utils/ts-ast' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/ts-utils/ts-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/ts-utils/typescript' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/vue2-builtin-components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/vue3-builtin-components' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-vue/lib/configs/base.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/base'>;
}
declare module 'eslint-plugin-vue/lib/configs/essential.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/essential'>;
}
declare module 'eslint-plugin-vue/lib/configs/no-layout-rules.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/no-layout-rules'>;
}
declare module 'eslint-plugin-vue/lib/configs/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/recommended'>;
}
declare module 'eslint-plugin-vue/lib/configs/strongly-recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/strongly-recommended'>;
}
declare module 'eslint-plugin-vue/lib/configs/vue3-essential.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/vue3-essential'>;
}
declare module 'eslint-plugin-vue/lib/configs/vue3-recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/vue3-recommended'>;
}
declare module 'eslint-plugin-vue/lib/configs/vue3-strongly-recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/vue3-strongly-recommended'>;
}
declare module 'eslint-plugin-vue/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib'>;
}
declare module 'eslint-plugin-vue/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib'>;
}
declare module 'eslint-plugin-vue/lib/meta.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/meta'>;
}
declare module 'eslint-plugin-vue/lib/processor.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/processor'>;
}
declare module 'eslint-plugin-vue/lib/removed-rules.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/removed-rules'>;
}
declare module 'eslint-plugin-vue/lib/rules/array-bracket-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/array-bracket-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/array-bracket-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/array-bracket-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/array-element-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/array-element-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/arrow-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/arrow-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/attribute-hyphenation.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/attribute-hyphenation'>;
}
declare module 'eslint-plugin-vue/lib/rules/attributes-order.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/attributes-order'>;
}
declare module 'eslint-plugin-vue/lib/rules/block-lang.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/block-lang'>;
}
declare module 'eslint-plugin-vue/lib/rules/block-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/block-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/block-tag-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/block-tag-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/brace-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/brace-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/camelcase.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/camelcase'>;
}
declare module 'eslint-plugin-vue/lib/rules/comma-dangle.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/comma-dangle'>;
}
declare module 'eslint-plugin-vue/lib/rules/comma-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/comma-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/comma-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/comma-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/comment-directive.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/comment-directive'>;
}
declare module 'eslint-plugin-vue/lib/rules/component-api-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/component-api-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/component-definition-name-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/component-definition-name-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/component-name-in-template-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/component-name-in-template-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/component-options-name-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/component-options-name-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/component-tags-order.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/component-tags-order'>;
}
declare module 'eslint-plugin-vue/lib/rules/custom-event-name-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/custom-event-name-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/define-emits-declaration.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/define-emits-declaration'>;
}
declare module 'eslint-plugin-vue/lib/rules/define-macros-order.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/define-macros-order'>;
}
declare module 'eslint-plugin-vue/lib/rules/define-props-declaration.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/define-props-declaration'>;
}
declare module 'eslint-plugin-vue/lib/rules/dot-location.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/dot-location'>;
}
declare module 'eslint-plugin-vue/lib/rules/dot-notation.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/dot-notation'>;
}
declare module 'eslint-plugin-vue/lib/rules/eqeqeq.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/eqeqeq'>;
}
declare module 'eslint-plugin-vue/lib/rules/first-attribute-linebreak.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/first-attribute-linebreak'>;
}
declare module 'eslint-plugin-vue/lib/rules/func-call-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/func-call-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-button-has-type.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-button-has-type'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-closing-bracket-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-closing-bracket-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-comment-content-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-comment-content-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-comment-content-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-comment-content-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-comment-indent.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-comment-indent'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-end-tags.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-end-tags'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-indent.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-indent'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-quotes.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-quotes'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-self-closing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-self-closing'>;
}
declare module 'eslint-plugin-vue/lib/rules/jsx-uses-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/jsx-uses-vars'>;
}
declare module 'eslint-plugin-vue/lib/rules/key-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/key-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/keyword-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/keyword-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/match-component-file-name.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/match-component-file-name'>;
}
declare module 'eslint-plugin-vue/lib/rules/match-component-import-name.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/match-component-import-name'>;
}
declare module 'eslint-plugin-vue/lib/rules/max-attributes-per-line.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/max-attributes-per-line'>;
}
declare module 'eslint-plugin-vue/lib/rules/max-len.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/max-len'>;
}
declare module 'eslint-plugin-vue/lib/rules/max-lines-per-block.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/max-lines-per-block'>;
}
declare module 'eslint-plugin-vue/lib/rules/multi-word-component-names.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/multi-word-component-names'>;
}
declare module 'eslint-plugin-vue/lib/rules/multiline-html-element-content-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/multiline-html-element-content-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/multiline-ternary.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/multiline-ternary'>;
}
declare module 'eslint-plugin-vue/lib/rules/mustache-interpolation-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/mustache-interpolation-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/new-line-between-multi-line-property.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/new-line-between-multi-line-property'>;
}
declare module 'eslint-plugin-vue/lib/rules/next-tick-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/next-tick-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-arrow-functions-in-watch.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-arrow-functions-in-watch'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-async-in-computed-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-async-in-computed-properties'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-bare-strings-in-template.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-bare-strings-in-template'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-boolean-default.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-boolean-default'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-child-content.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-child-content'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-computed-properties-in-data.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-computed-properties-in-data'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-console.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-console'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-constant-condition.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-constant-condition'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-custom-modifiers-on-v-model.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-custom-modifiers-on-v-model'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-data-object-declaration.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-data-object-declaration'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-destroyed-lifecycle.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-destroyed-lifecycle'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-dollar-listeners-api.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-dollar-listeners-api'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-dollar-scopedslots-api.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-dollar-scopedslots-api'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-events-api.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-events-api'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-filter.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-filter'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-functional-template.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-functional-template'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-html-element-is.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-html-element-is'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-inline-template.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-inline-template'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-props-default-this.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-props-default-this'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-router-link-tag-prop.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-router-link-tag-prop'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-scope-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-scope-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-slot-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-slot-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-slot-scope-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-slot-scope-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-v-bind-sync.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-v-bind-sync'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-v-is.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-v-is'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-v-on-native-modifier.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-v-on-native-modifier'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-v-on-number-modifiers.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-v-on-number-modifiers'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-vue-config-keycodes.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-vue-config-keycodes'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-dupe-keys.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-dupe-keys'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-dupe-v-else-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-dupe-v-else-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-duplicate-attr-inheritance.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-duplicate-attr-inheritance'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-duplicate-attributes.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-duplicate-attributes'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-empty-component-block.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-empty-component-block'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-empty-pattern.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-empty-pattern'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-export-in-script-setup.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-export-in-script-setup'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-expose-after-await.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-expose-after-await'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-extra-parens.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-extra-parens'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-invalid-model-keys.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-invalid-model-keys'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-irregular-whitespace.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-irregular-whitespace'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-lifecycle-after-await.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-lifecycle-after-await'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-lone-template.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-lone-template'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-loss-of-precision.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-loss-of-precision'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-multi-spaces.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-multi-spaces'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-multiple-objects-in-class.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-multiple-objects-in-class'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-multiple-slot-args.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-multiple-slot-args'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-multiple-template-root.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-multiple-template-root'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-mutating-props.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-mutating-props'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-parsing-error.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-parsing-error'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-potential-component-option-typo.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-potential-component-option-typo'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-ref-as-operand.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-ref-as-operand'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-ref-object-destructure.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-ref-object-destructure'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-required-prop-with-default.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-required-prop-with-default'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-reserved-component-names.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-reserved-component-names'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-reserved-keys.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-reserved-keys'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-reserved-props.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-reserved-props'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-block.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-block'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-call-after-await.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-call-after-await'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-class.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-class'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-component-names.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-component-names'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-component-options.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-component-options'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-custom-event.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-custom-event'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-html-elements.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-html-elements'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-props.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-props'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-static-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-static-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-syntax.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-syntax'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-v-bind.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-v-bind'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-root-v-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-root-v-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-setup-props-destructure.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-setup-props-destructure'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-shared-component-data.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-shared-component-data'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-side-effects-in-computed-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-side-effects-in-computed-properties'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-spaces-around-equal-signs-in-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-spaces-around-equal-signs-in-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-sparse-arrays.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-sparse-arrays'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-static-inline-styles.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-static-inline-styles'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-template-key.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-template-key'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-template-shadow.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-template-shadow'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-template-target-blank.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-template-target-blank'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-textarea-mustache.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-textarea-mustache'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-this-in-before-route-enter.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-this-in-before-route-enter'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-undef-components.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-undef-components'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-undef-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-undef-properties'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-unsupported-features.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-unsupported-features'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-unused-components.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-unused-components'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-unused-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-unused-properties'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-unused-refs.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-unused-refs'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-unused-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-unused-vars'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-use-computed-property-like-method.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-use-computed-property-like-method'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-use-v-if-with-v-for.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-use-v-if-with-v-for'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-useless-concat.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-useless-concat'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-useless-mustaches.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-useless-mustaches'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-useless-template-attributes.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-useless-template-attributes'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-useless-v-bind.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-useless-v-bind'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-v-for-template-key-on-child.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-v-for-template-key-on-child'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-v-for-template-key.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-v-for-template-key'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-v-html.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-v-html'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-v-model-argument.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-v-model-argument'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-v-text-v-html-on-component.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-v-text-v-html-on-component'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-v-text.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-v-text'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-watch-after-await.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-watch-after-await'>;
}
declare module 'eslint-plugin-vue/lib/rules/object-curly-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/object-curly-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/object-curly-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/object-curly-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/object-property-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/object-property-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/object-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/object-shorthand'>;
}
declare module 'eslint-plugin-vue/lib/rules/one-component-per-file.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/one-component-per-file'>;
}
declare module 'eslint-plugin-vue/lib/rules/operator-linebreak.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/operator-linebreak'>;
}
declare module 'eslint-plugin-vue/lib/rules/order-in-components.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/order-in-components'>;
}
declare module 'eslint-plugin-vue/lib/rules/padding-line-between-blocks.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/padding-line-between-blocks'>;
}
declare module 'eslint-plugin-vue/lib/rules/padding-line-between-tags.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/padding-line-between-tags'>;
}
declare module 'eslint-plugin-vue/lib/rules/padding-lines-in-component-definition.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/padding-lines-in-component-definition'>;
}
declare module 'eslint-plugin-vue/lib/rules/prefer-define-options.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/prefer-define-options'>;
}
declare module 'eslint-plugin-vue/lib/rules/prefer-import-from-vue.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/prefer-import-from-vue'>;
}
declare module 'eslint-plugin-vue/lib/rules/prefer-prop-type-boolean-first.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/prefer-prop-type-boolean-first'>;
}
declare module 'eslint-plugin-vue/lib/rules/prefer-separate-static-class.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/prefer-separate-static-class'>;
}
declare module 'eslint-plugin-vue/lib/rules/prefer-template.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/prefer-template'>;
}
declare module 'eslint-plugin-vue/lib/rules/prefer-true-attribute-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/prefer-true-attribute-shorthand'>;
}
declare module 'eslint-plugin-vue/lib/rules/prop-name-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/prop-name-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/quote-props.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/quote-props'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-component-is.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-component-is'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-default-prop.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-default-prop'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-direct-export.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-direct-export'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-emit-validator.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-emit-validator'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-explicit-emits.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-explicit-emits'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-expose.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-expose'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-macro-variable-name.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-macro-variable-name'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-name-property.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-name-property'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-prop-comment.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-prop-comment'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-prop-type-constructor.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-prop-type-constructor'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-prop-types.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-prop-types'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-render-return.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-render-return'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-slots-as-functions.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-slots-as-functions'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-toggle-inside-transition.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-toggle-inside-transition'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-typed-ref.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-typed-ref'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-v-for-key.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-v-for-key'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-valid-default-prop.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-valid-default-prop'>;
}
declare module 'eslint-plugin-vue/lib/rules/return-in-computed-property.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/return-in-computed-property'>;
}
declare module 'eslint-plugin-vue/lib/rules/return-in-emits-validator.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/return-in-emits-validator'>;
}
declare module 'eslint-plugin-vue/lib/rules/script-indent.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/script-indent'>;
}
declare module 'eslint-plugin-vue/lib/rules/script-setup-uses-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/script-setup-uses-vars'>;
}
declare module 'eslint-plugin-vue/lib/rules/singleline-html-element-content-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/singleline-html-element-content-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/sort-keys.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/sort-keys'>;
}
declare module 'eslint-plugin-vue/lib/rules/space-in-parens.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/space-in-parens'>;
}
declare module 'eslint-plugin-vue/lib/rules/space-infix-ops.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/space-infix-ops'>;
}
declare module 'eslint-plugin-vue/lib/rules/space-unary-ops.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/space-unary-ops'>;
}
declare module 'eslint-plugin-vue/lib/rules/static-class-names-order.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/static-class-names-order'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/define-options.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/define-options'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/define-slots.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/define-slots'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/dynamic-directive-arguments.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/dynamic-directive-arguments'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/is-attribute-with-vue-prefix.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/is-attribute-with-vue-prefix'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/scope-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/scope-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/script-setup.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/script-setup'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/slot-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/slot-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/slot-scope-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/slot-scope-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/style-css-vars-injection.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/style-css-vars-injection'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/utils/can-convert-to-v-slot.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/utils/can-convert-to-v-slot'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-bind-attr-modifier.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/v-bind-attr-modifier'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-bind-prop-modifier-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/v-bind-prop-modifier-shorthand'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-is.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/v-is'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-memo.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/v-memo'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-model-argument.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/v-model-argument'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-model-custom-modifiers.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/v-model-custom-modifiers'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-slot.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/v-slot'>;
}
declare module 'eslint-plugin-vue/lib/rules/template-curly-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/template-curly-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/this-in-template.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/this-in-template'>;
}
declare module 'eslint-plugin-vue/lib/rules/use-v-on-exact.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/use-v-on-exact'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-bind-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-bind-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-for-delimiter-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-for-delimiter-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-on-event-hyphenation.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-on-event-hyphenation'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-on-function-call.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-on-function-call'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-on-handler-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-on-handler-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-on-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-on-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-slot-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-slot-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-attribute-name.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-attribute-name'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-define-emits.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-define-emits'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-define-options.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-define-options'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-define-props.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-define-props'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-model-definition.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-model-definition'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-next-tick.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-next-tick'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-template-root.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-template-root'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-bind-sync.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-bind-sync'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-bind.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-bind'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-cloak.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-cloak'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-else-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-else-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-else.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-else'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-for.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-for'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-html.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-html'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-is.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-is'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-memo.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-memo'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-model.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-model'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-on.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-on'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-once.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-once'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-pre.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-pre'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-show.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-show'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-slot.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-slot'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-text.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-text'>;
}
declare module 'eslint-plugin-vue/lib/utils/casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/casing'>;
}
declare module 'eslint-plugin-vue/lib/utils/comments.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/comments'>;
}
declare module 'eslint-plugin-vue/lib/utils/html-comments.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/html-comments'>;
}
declare module 'eslint-plugin-vue/lib/utils/indent-common.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/indent-common'>;
}
declare module 'eslint-plugin-vue/lib/utils/indent-ts.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/indent-ts'>;
}
declare module 'eslint-plugin-vue/lib/utils/indent-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/indent-utils'>;
}
declare module 'eslint-plugin-vue/lib/utils/index' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils'>;
}
declare module 'eslint-plugin-vue/lib/utils/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils'>;
}
declare module 'eslint-plugin-vue/lib/utils/keycode-to-key.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/keycode-to-key'>;
}
declare module 'eslint-plugin-vue/lib/utils/property-references.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/property-references'>;
}
declare module 'eslint-plugin-vue/lib/utils/ref-object-references.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/ref-object-references'>;
}
declare module 'eslint-plugin-vue/lib/utils/regexp.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/regexp'>;
}
declare module 'eslint-plugin-vue/lib/utils/selector.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/selector'>;
}
declare module 'eslint-plugin-vue/lib/utils/style-variables/index' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/style-variables'>;
}
declare module 'eslint-plugin-vue/lib/utils/style-variables/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/style-variables'>;
}
declare module 'eslint-plugin-vue/lib/utils/ts-utils/index' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/ts-utils'>;
}
declare module 'eslint-plugin-vue/lib/utils/ts-utils/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/ts-utils'>;
}
declare module 'eslint-plugin-vue/lib/utils/ts-utils/ts-ast.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/ts-utils/ts-ast'>;
}
declare module 'eslint-plugin-vue/lib/utils/ts-utils/ts-types.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/ts-utils/ts-types'>;
}
declare module 'eslint-plugin-vue/lib/utils/ts-utils/typescript.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/ts-utils/typescript'>;
}
declare module 'eslint-plugin-vue/lib/utils/vue2-builtin-components.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/vue2-builtin-components'>;
}
declare module 'eslint-plugin-vue/lib/utils/vue3-builtin-components.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/vue3-builtin-components'>;
}
