// flow-typed signature: 713087585b633e978f781fd62b4b165c
// flow-typed version: <<STUB>>/js-cookie_v^3.0.5/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-cookie/dist/js.cookie' {
  declare module.exports: any;
}

declare module 'js-cookie/dist/js.cookie.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-cookie/dist/js.cookie.js' {
  declare module.exports: $Exports<'js-cookie/dist/js.cookie'>;
}
declare module 'js-cookie/dist/js.cookie.min.js' {
  declare module.exports: $Exports<'js-cookie/dist/js.cookie.min'>;
}
declare module 'js-cookie/index' {
  declare module.exports: $Exports<'js-cookie'>;
}
declare module 'js-cookie/index.js' {
  declare module.exports: $Exports<'js-cookie'>;
}
