// flow-typed signature: 78af63cc7c2d47d4e4b37dfb71d86e9e
// flow-typed version: <<STUB>>/pinia_v^2.0.0/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pinia'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pinia' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pinia/dist/pinia.esm-browser' {
  declare module.exports: any;
}

declare module 'pinia/dist/pinia.iife' {
  declare module.exports: any;
}

declare module 'pinia/dist/pinia.iife.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pinia/dist/pinia.esm-browser.js' {
  declare module.exports: $Exports<'pinia/dist/pinia.esm-browser'>;
}
declare module 'pinia/dist/pinia.iife.js' {
  declare module.exports: $Exports<'pinia/dist/pinia.iife'>;
}
declare module 'pinia/dist/pinia.iife.prod.js' {
  declare module.exports: $Exports<'pinia/dist/pinia.iife.prod'>;
}
declare module 'pinia/index' {
  declare module.exports: $Exports<'pinia'>;
}
declare module 'pinia/index.js' {
  declare module.exports: $Exports<'pinia'>;
}
