// flow-typed signature: d0ac7411ce81e1902f44ae5e6365c37f
// flow-typed version: <<STUB>>/vite-plugin-vuetify_v^1.0.0/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-plugin-vuetify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-plugin-vuetify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite-plugin-vuetify/dist/importPlugin' {
  declare module.exports: any;
}

declare module 'vite-plugin-vuetify/dist' {
  declare module.exports: any;
}

declare module 'vite-plugin-vuetify/dist/stylesPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite-plugin-vuetify/dist/importPlugin.js' {
  declare module.exports: $Exports<'vite-plugin-vuetify/dist/importPlugin'>;
}
declare module 'vite-plugin-vuetify/dist/index' {
  declare module.exports: $Exports<'vite-plugin-vuetify/dist'>;
}
declare module 'vite-plugin-vuetify/dist/index.js' {
  declare module.exports: $Exports<'vite-plugin-vuetify/dist'>;
}
declare module 'vite-plugin-vuetify/dist/stylesPlugin.js' {
  declare module.exports: $Exports<'vite-plugin-vuetify/dist/stylesPlugin'>;
}
