// flow-typed signature: 425d4a6151ed88ef13495ef66b8c9023
// flow-typed version: <<STUB>>/vuetify_v^3.0.0/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuetify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuetify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuetify/dist/vuetify-labs.esm' {
  declare module.exports: any;
}

declare module 'vuetify/dist/vuetify-labs' {
  declare module.exports: any;
}

declare module 'vuetify/dist/vuetify.esm' {
  declare module.exports: any;
}

declare module 'vuetify/dist/vuetify' {
  declare module.exports: any;
}

declare module 'vuetify/dist/vuetify.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuetify/dist/vuetify-labs.esm.js' {
  declare module.exports: $Exports<'vuetify/dist/vuetify-labs.esm'>;
}
declare module 'vuetify/dist/vuetify-labs.js' {
  declare module.exports: $Exports<'vuetify/dist/vuetify-labs'>;
}
declare module 'vuetify/dist/vuetify.esm.js' {
  declare module.exports: $Exports<'vuetify/dist/vuetify.esm'>;
}
declare module 'vuetify/dist/vuetify.js' {
  declare module.exports: $Exports<'vuetify/dist/vuetify'>;
}
declare module 'vuetify/dist/vuetify.min.js' {
  declare module.exports: $Exports<'vuetify/dist/vuetify.min'>;
}
