// flow-typed signature: 25c1fc84bc32e21f65e5ae55e884158b
// flow-typed version: <<STUB>>/@mdi/font_v7.0.96/flow_v0.214.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdi/font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdi/font' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mdi/font/scripts/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mdi/font/scripts/verify.js' {
  declare module.exports: $Exports<'@mdi/font/scripts/verify'>;
}
