FROM mambaorg/micromamba:1.4.7-bionic-cuda-11.3.1

USER root
# Keep the base environment activated
ARG MAMBA_DOCKERFILE_ACTIVATE=1
ENV MAMBA_REMOTE_CONNECT_TIMEOUT_SECS=60 \
    MAMBA_REMOTE_READ_TIMEOUT_SECS=600 \
    MAMBA_REMOTE_MAX_RETRIES=5
RUN apt update && apt -y install gcc g++ make

# Use micromamba to resolve conda-forge, much faster than conda
RUN micromamba install -y python=3.7 pip=20.0.2 cudatoolkit=11.2 rdkit=2020.09.5 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install \
    fastapi==0.95.1 \
    nvidia-cudnn-cu11==8.9.1.23 \
    protobuf==3.19.0 \
    pydantic==1.10.12 \
    rdchiral==1.1.0 \
    requests==2.31.0 \
    scikit-learn==1.0.2 \
    scipy==1.7.3 \
    tensorflow==2.7.4 \
    urllib3==1.26.16 \
    uvicorn==0.21.1 \
    zipp==3.20.2

# CUDA postprocessing per tf documentation
RUN mkdir -p $CONDA_PREFIX/etc/conda/activate.d
RUN echo 'CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' \
    >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
RUN echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' \
    >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
RUN source $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh

COPY . /app/general_selectivity
WORKDIR /app/general_selectivity

EXPOSE 9641

CMD ["python", "general_selectivity_server.py"]
